/**
 * Market analysis data by source country (UK, Ukraine, Spain).
 * Each country has en/uk/es variants; combine with I18N for structural labels.
 */
const MA_DATA = {
  uk: {
    en: {
    ma_s1_region: 'UK Market',
    ma_s1_r1_src: 'eBay / Private Listings',
    ma_s1_r1_type: 'Unrestored carriages',
    ma_s1_r1_price: '£1,500 – £5,000',
    ma_s1_r1_notes: 'Often heritage Mark 1/2; condition varies',
    ma_s1_r2_src: 'Converted / Part-Restored',
    ma_s1_r2_type: 'Holiday let / residential',
    ma_s1_r2_price: '£50,000 – £70,000',
    ma_s1_r2_notes: 'E.g. Stannington Pullman (1978 Mark 3) sold 2024',
    ma_s1_r3_src: 'Heritage Societies & Auctions',
    ma_s1_r3_type: 'Mark 1, Gresley teak',
    ma_s1_r3_price: '£8,000 – £30,000+',
    ma_s1_r3_notes: 'G.W. Railwayana; Heritage Railway Magazine',
    ma_s1_r4_src: 'Rolling Stock Lessors',
    ma_s1_r4_type: 'Class 319, 325, HST',
    ma_s1_r4_price: 'Scrap / negotiated',
    ma_s1_r4_notes: 'Some open to sale (e.g. Royal Mail Class 325)',
    ma_s1_f1: 'Class 319 (London Northwestern) — scrapped as Class 730 enters',
    ma_s1_f2: 'Class 325 (Royal Mail) — some scrapped; operator open to selling remainder',
    ma_s1_f3: 'Class 507 (Merseyside) — scrapped as Class 777 enters',
    ma_s1_f4: 'HST Power Cars — some scrapped; Mark 3 coaches may become available',
    ma_s1_d1_type: 'Mark 1', ma_s1_d1_len: '17–20 m', ma_s1_d1_wt: '~35 tonnes', ma_s1_d1_best: '4–6 person office',
    ma_s1_d2_type: 'Mark 2', ma_s1_d2_len: '~19 m', ma_s1_d2_wt: '~32 tonnes', ma_s1_d2_best: '4–6 person office',
    ma_s1_d3_type: 'Mark 3', ma_s1_d3_len: '23 m (75 ft)', ma_s1_d3_wt: '~35 tonnes', ma_s1_d3_best: '6–10 person office',
    ma_s1_concl: 'Supply exists but is fragmented. Heritage Mark 1/2 are most accessible; Mark 3 and modern stock come via operators during fleet replacement.',
    ma_s2_trans_p: 'Allelys (UK leader). Methods: ramp + winch, low-loader, crane when needed.',
    ma_s2_r1_d: '30 miles', ma_s2_r1_c: '£10,000–£15,000',
    ma_s2_r2_d: '100 miles', ma_s2_r2_c: '£15,000–£25,000',
    ma_s2_r3_d: '200+ miles', ma_s2_r3_c: '£25,000–£40,000+',
    ma_s2_req: 'Abnormal load permits (AIL), police escort for wide loads, route surveys, site access.',
    ma_s2_siting_p: 'Heritage lines often require road delivery. Urban sites need landowner agreement, planning, and services (power, water, drainage). Station platforms possible where Network Rail / TOC allows.',
    ma_s3_p1: '~USD 1.4B (2024), ~13–14% CAGR → ~USD 3.7–4B by 2033. Drivers: hybrid work, wellbeing, lack of private space.',
    ma_s3_p2: '£49–51/sq ft (Workspace Group); prime London £200+/sq ft.',
    ma_s3_r1_p: 'Spacestor Railway Carriage (new)', ma_s3_r1_pr: '£5,400–£17,400 + VAT', ma_s3_r1_c: '2–6 people',
    ma_s3_r2_p: 'Hot desk membership', ma_s3_r2_pr: '£150–£550/month', ma_s3_r2_c: '1',
    ma_s3_r3_p: 'Private office', ma_s3_r3_pr: '£500–£1,500+/desk/month', ma_s3_r3_c: '2–10',
    ma_s3_pos: 'Real carriages, heritage character, larger footprint (4–10 people). Target: SMEs, creative agencies, remote teams, coworking operators.',
    ma_s4_r1_proc: '£5,000', ma_s4_r1_trans: '£12,000', ma_s4_r1_conv: '£40,000', ma_s4_r1_tot: '£57,000',
    ma_s4_r2_proc: '£15,000', ma_s4_r2_trans: '£20,000', ma_s4_r2_conv: '£100,000', ma_s4_r2_tot: '£135,000',
    ma_s4_r3_proc: '£35,000', ma_s4_r3_trans: '£25,000', ma_s4_r3_conv: '£150,000', ma_s4_r3_tot: '£210,000',
    ma_s5_p1: '4-person cabin: £2,000–£3,500/month revenue at £600–£900/desk. Payback: ~4–5 years at 75–80% occupancy. Pricing at £800+/desk or strong room-hire mix improves viability.',
    ma_s5_p2: 'Portfolio of 5–10 cabins improves margins. B2B and corporate lets improve unit economics.',
    ma_s6_r1_r: 'Supply volatility', ma_s6_r1_m: 'Lock options with preservation societies; engage lessors during fleet replacement',
    ma_s6_r2_r: 'Transport cost', ma_s6_r2_m: 'Site carriage near source; batch moves',
    ma_s6_r3_r: 'Planning', ma_s6_r3_m: 'Early engagement with planners; permitted development where possible',
    ma_s6_r4_r: 'Land access', ma_s6_r4_m: 'Partner with landowners (stations, business parks, heritage lines)',
    ma_s7_r1_f: 'Availability', ma_s7_r1_a: 'Moderate — heritage carriages accessible; Mark 3 via operators',
    ma_s7_r2_f: 'Logistics', ma_s7_r2_a: 'Manageable — specialist hauliers exist',
    ma_s7_r3_f: 'Demand', ma_s7_r3_a: 'Strong — office pod market growing',
    ma_s7_r4_f: 'CapEx per cabin', ma_s7_r4_a: '£57k–£210k depending on spec',
    ma_s7_r5_f: 'ROI', ma_s7_r5_a: '4–5 year payback feasible at 75–80% occupancy',
    ma_s7_rec: 'Pilot with 1–2 carriages (Mark 1 or 2) at a single site. Target £80–100k all-in per cabin, premium pricing (£800+/desk), and a partner with land. Validate demand before scaling.',
    ma_sources: 'Sources: Rail Magazine, Heritage Railway, Ty Green, Spacestor, Workspace Group, CoworkingCafe, Allelys. Figures are indicative.',
    },
    uk: {},
    es: {},
  },

  ua: {
    en: {
    ma_s1_region: 'Ukraine Market',
    ma_s1_r1_src: 'OLX / Private Listings',
    ma_s1_r1_type: 'Unrestored Soviet-era carriages',
    ma_s1_r1_price: '₴50,000 – ₴150,000',
    ma_s1_r1_notes: 'Often 61-417, 61-444; condition varies',
    ma_s1_r2_src: 'Converted / Part-Restored',
    ma_s1_r2_type: 'Holiday let / café',
    ma_s1_r2_price: '₴800,000 – ₴1.2M',
    ma_s1_r2_notes: 'Examples from Carpathian region',
    ma_s1_r3_src: 'Ukrzaliznytsia & Museums',
    ma_s1_r3_type: '61-417, 61-444, compartment cars',
    ma_s1_r3_price: '₴200,000 – ₴600,000+',
    ma_s1_r3_notes: 'UZ surplus; Railway Museum Kyiv',
    ma_s1_r4_src: 'UZ Fleet Replacement',
    ma_s1_r4_type: 'Older intercity stock',
    ma_s1_r4_price: 'Scrap / negotiated',
    ma_s1_r4_notes: 'Some available during fleet modernisation',
    ma_s1_f1: '61-417 / 61-444 — phased out on regional routes',
    ma_s1_f2: 'Compartment cars (Купе) — surplus on some lines',
    ma_s1_f3: 'Older electric units — replaced by Hyundai Rotem',
    ma_s1_f4: 'Sleeping cars — some decommissioned; museums interested',
    ma_s1_d1_type: '61-417', ma_s1_d1_len: '24 m', ma_s1_d1_wt: '~40 tonnes', ma_s1_d1_best: '4–6 person office',
    ma_s1_d2_type: '61-444', ma_s1_d2_len: '24 m', ma_s1_d2_wt: '~42 tonnes', ma_s1_d2_best: '4–8 person office',
    ma_s1_d3_type: 'Compartment', ma_s1_d3_len: '24 m', ma_s1_d3_wt: '~45 tonnes', ma_s1_d3_best: '6–10 person office',
    ma_s1_concl: 'Supply exists via UZ surplus and private sellers. Soviet-era stock most accessible; modernisation creates periodic availability. War damage and scrap demand affect pricing.',
    ma_s2_trans_p: 'Heavy haulers (ТОВ Транспорт, local operators). Methods: low-loader, crane. Road conditions and permits vary by region.',
    ma_s2_r1_d: '50 km', ma_s2_r1_c: '₴80,000–₴150,000',
    ma_s2_r2_d: '200 km', ma_s2_r2_c: '₴200,000–₴350,000',
    ma_s2_r3_d: '500+ km', ma_s2_r3_c: '₴400,000–₴700,000+',
    ma_s2_req: 'Oversize permits, route surveys (bridge limits), site access. Checkpoints may require coordination.',
    ma_s2_siting_p: 'Urban sites need landowner agreement, planning. Station sidings possible where UZ allows. Power and utilities vary by location.',
    ma_s3_p1: '~USD 0.3B (2024), growing post-war. Drivers: reconstruction, remote work, demand for flexible spaces in safer regions.',
    ma_s3_p2: 'Kyiv/Lviv flexible office: €8–15/m²; premium locations €20+/m².',
    ma_s3_r1_p: 'Local pod solutions', ma_s3_r1_pr: '₴150,000–₴400,000 + VAT', ma_s3_r1_c: '2–4 people',
    ma_s3_r2_p: 'Hot desk membership', ma_s3_r2_pr: '₴3,000–₴12,000/month', ma_s3_r2_c: '1',
    ma_s3_r3_p: 'Private office', ma_s3_r3_pr: '₴8,000–₴25,000/desk/month', ma_s3_r3_c: '2–10',
    ma_s3_pos: 'Real carriages, Soviet heritage character, larger footprint. Target: SMEs, NGOs, remote teams, coworking in Lviv, Kyiv, Odesa.',
    ma_s4_r1_proc: '₴200,000', ma_s4_r1_trans: '₴150,000', ma_s4_r1_conv: '₴1.2M', ma_s4_r1_tot: '₴1.55M',
    ma_s4_r2_proc: '₴500,000', ma_s4_r2_trans: '₴300,000', ma_s4_r2_conv: '₴2.5M', ma_s4_r2_tot: '₴3.3M',
    ma_s4_r3_proc: '₴1M', ma_s4_r3_trans: '₴500,000', ma_s4_r3_conv: '₴4M', ma_s4_r3_tot: '₴5.5M',
    ma_s5_p1: '4-person cabin: ₴40,000–₴80,000/month at ₴10,000–₴20,000/desk. Payback: ~4–6 years at 70–80% occupancy. Premium pricing in Kyiv/Lviv improves viability.',
    ma_s5_p2: 'Portfolio of 3–5 cabins improves margins. B2B and NGO lets improve unit economics.',
    ma_s6_r1_r: 'Supply volatility', ma_s6_r1_m: 'Engage UZ during fleet replacement; consider private sellers',
    ma_s6_r2_r: 'Transport & road conditions', ma_s6_r2_m: 'Site near source; factor bridge/road limits',
    ma_s6_r3_r: 'Planning & permits', ma_s6_r3_m: 'Early engagement with local authorities',
    ma_s6_r4_r: 'Land access', ma_s6_r4_m: 'Partner with stations, business parks, municipalities',
    ma_s7_r1_f: 'Availability', ma_s7_r1_a: 'Moderate — Soviet stock accessible; UZ surplus periodic',
    ma_s7_r2_f: 'Logistics', ma_s7_r2_a: 'Manageable — hauliers exist; road conditions vary',
    ma_s7_r3_f: 'Demand', ma_s7_r3_a: 'Growing — reconstruction, remote work, flexible space',
    ma_s7_r4_f: 'CapEx per cabin', ma_s7_r4_a: '₴1.5M–₴5.5M depending on spec',
    ma_s7_r5_f: 'ROI', ma_s7_r5_a: '4–6 year payback feasible at 70–80% occupancy',
    ma_s7_rec: 'Pilot with 1–2 carriages in Lviv or Kyiv. Target ₴1.5–3M all-in per cabin, premium pricing. Validate demand in safer regions before scaling.',
    ma_sources: 'Sources: Ukrzaliznytsia, Railway Museum Kyiv, local hauliers, coworking operators. Figures are indicative.',
    },
    uk: {
      ma_s1_region: 'Ринок України',
      ma_s1_r1_src: 'OLX / Приватні оголошення',
      ma_s1_r1_type: 'Невідновлені радянські вагони',
      ma_s1_r1_price: '₴50,000 – ₴150,000',
      ma_s1_r1_notes: 'Часто 61-417, 61-444; стан різний',
      ma_s1_r2_src: 'Переобладнані / Частково відновлені',
      ma_s1_r2_type: 'Оренда для відпочинку / кафе',
      ma_s1_r2_price: '₴800,000 – ₴1.2M',
      ma_s1_r2_notes: 'Приклади з Карпатського регіону',
      ma_s1_r3_src: 'Укрзалізниця та музеї',
      ma_s1_r3_type: '61-417, 61-444, вагони купе',
      ma_s1_r3_price: '₴200,000 – ₴600,000+',
      ma_s1_r3_notes: 'Надлишок УЗ; Залізничний музей Києва',
      ma_s1_r4_src: 'Заміна флоту УЗ',
      ma_s1_r4_type: 'Старі міжміські вагони',
      ma_s1_r4_price: 'На металобрухт / переговори',
      ma_s1_r4_notes: 'Доступні під час модернізації флоту',
      ma_s1_f1: '61-417 / 61-444 — виведення з регіональних маршрутів',
      ma_s1_f2: 'Вагони купе — надлишок на деяких лініях',
      ma_s1_f3: 'Старі електропоїзди — заміна на Hyundai Rotem',
      ma_s1_f4: 'Спальні вагони — частина списана; музеї зацікавлені',
      ma_s1_d1_type: '61-417', ma_s1_d1_len: '24 м', ma_s1_d1_wt: '~40 тонн', ma_s1_d1_best: 'Офіс на 4–6 осіб',
      ma_s1_d2_type: '61-444', ma_s1_d2_len: '24 м', ma_s1_d2_wt: '~42 тонни', ma_s1_d2_best: 'Офіс на 4–8 осіб',
      ma_s1_d3_type: 'Купе', ma_s1_d3_len: '24 м', ma_s1_d3_wt: '~45 тонн', ma_s1_d3_best: 'Офіс на 6–10 осіб',
      ma_s1_concl: 'Пропозиція є через надлишок УЗ та приватних продавців. Радянський склад найдоступніший; модернізація створює періодичну доступність. Війна та попит на металобрухт впливають на ціни.',
      ma_s2_trans_p: 'Важкі перевізники (ТОВ Транспорт, місцеві). Методи: низькорамний причіп, кран. Стан доріг та дозволи різняться за регіонами.',
      ma_s2_r1_d: '50 км', ma_s2_r1_c: '₴80,000–₴150,000',
      ma_s2_r2_d: '200 км', ma_s2_r2_c: '₴200,000–₴350,000',
      ma_s2_r3_d: '500+ км', ma_s2_r3_c: '₴400,000–₴700,000+',
      ma_s2_req: 'Дозволи на негабарит, обстеження маршруту (містки), доступ до майданчика. КПП можуть потребувати узгодження.',
      ma_s2_siting_p: 'Міські ділянки — угода з власником, планування. Колійні тупики можливі за згодою УЗ. Електрика та комунікації різняться.',
      ma_s3_p1: '~USD 0.3B (2024), зростання після війни. Драйвери: відбудова, віддалена робота, попит на гнучкі простори в безпечніших регіонах.',
      ma_s3_p2: 'Київ/Львів гнучкий офіс: €8–15/м²; преміум €20+/м².',
      ma_s3_r1_p: 'Місцеві поди', ma_s3_r1_pr: '₴150,000–₴400,000 + ПДВ', ma_s3_r1_c: '2–4 особи',
      ma_s3_r2_p: 'Hot desk підписка', ma_s3_r2_pr: '₴3,000–₴12,000/міс', ma_s3_r2_c: '1',
      ma_s3_r3_p: 'Приватний офіс', ma_s3_r3_pr: '₴8,000–₴25,000/стіл/міс', ma_s3_r3_c: '2–10',
      ma_s3_pos: 'Справжні вагони, радянський характер, більший простір. Ціль: МСП, НГО, віддалені команди, коворкінги у Львові, Києві, Одесі.',
      ma_s4_r1_proc: '₴200,000', ma_s4_r1_trans: '₴150,000', ma_s4_r1_conv: '₴1.2M', ma_s4_r1_tot: '₴1.55M',
      ma_s4_r2_proc: '₴500,000', ma_s4_r2_trans: '₴300,000', ma_s4_r2_conv: '₴2.5M', ma_s4_r2_tot: '₴3.3M',
      ma_s4_r3_proc: '₴1M', ma_s4_r3_trans: '₴500,000', ma_s4_r3_conv: '₴4M', ma_s4_r3_tot: '₴5.5M',
      ma_s5_p1: 'Кабіна на 4 особи: ₴40,000–₴80,000/міс при ₴10,000–₴20,000/стіл. Окупність: ~4–6 років при 70–80% завантаженні. Преміум-ціни в Києві/Львові покращують життєздатність.',
      ma_s5_p2: 'Портфель 3–5 кабін покращує маржу. B2B та оренди для НГО покращують unit economics.',
      ma_s6_r1_r: 'Волатильність пропозиції', ma_s6_r1_m: 'Залучати УЗ під час заміни флоту; розглянути приватних продавців',
      ma_s6_r2_r: 'Транспорт та стан доріг', ma_s6_r2_m: 'Майданчик ближче до джерела; враховувати обмеження мостів',
      ma_s6_r3_r: 'Планування та дозволи', ma_s6_r3_m: 'Рання взаємодія з місцевою владою',
      ma_s6_r4_r: 'Доступ до землі', ma_s6_r4_m: 'Партнерство зі станціями, бізнес-парками, муніципалітетами',
      ma_s7_r1_f: 'Наявність', ma_s7_r1_a: 'Помірна — радянський склад доступний; надлишок УЗ періодичний',
      ma_s7_r2_f: 'Логістика', ma_s7_r2_a: 'Керована — є перевізники; стан доріг різний',
      ma_s7_r3_f: 'Попит', ma_s7_r3_a: 'Зростає — відбудова, віддалена робота, гнучкий простір',
      ma_s7_r4_f: 'CapEx на кабіну', ma_s7_r4_a: '₴1.5M–₴5.5M залежно від специфікації',
      ma_s7_r5_f: 'ROI', ma_s7_r5_a: 'Окупність 4–6 років при 70–80% завантаженні',
      ma_s7_rec: 'Пілот з 1–2 вагонами у Львові або Києві. Ціль ₴1.5–3M загалом на кабіну, преміум-ціни. Перевірити попит у безпечніших регіонах перед масштабуванням.',
      ma_sources: 'Джерела: Укрзалізниця, Залізничний музей Києва, місцеві перевізники, оператори коворкінгів. Цифри орієнтовні.',
    },
    es: {},
  },

  es: {
    en: {
    ma_s1_region: 'Spain Market',
    ma_s1_r1_src: 'Milanuncios / Auctions',
    ma_s1_r1_type: 'Unrestored carriages',
    ma_s1_r1_price: '€2,000 – €8,000',
    ma_s1_r1_notes: 'Often old Renfe/FEVE stock',
    ma_s1_r2_src: 'Converted / Part-Restored',
    ma_s1_r2_type: 'Holiday let / hotel',
    ma_s1_r2_price: '€40,000 – €90,000',
    ma_s1_r2_notes: 'E.g. railway hotels in Galicia, Asturias',
    ma_s1_r3_src: 'Renfe / FEVE / Museums',
    ma_s1_r3_type: 'Serie 440, 592, old Talgo',
    ma_s1_r3_price: '€10,000 – €50,000+',
    ma_s1_r3_notes: 'Retired stock sales; periodic auctions',
    ma_s1_r4_src: 'Rolling Stock Lessors',
    ma_s1_r4_type: 'Serie 440, 592, old units',
    ma_s1_r4_price: 'Scrap / negotiated',
    ma_s1_r4_notes: 'Renfe sells to scrap; contact during fleet replacement',
    ma_s1_f1: 'Serie 440 (Cercanías) — progressive withdrawal',
    ma_s1_f2: 'Serie 592 (Media Distancia) — replaced by Civia',
    ma_s1_f3: 'Talgo III/IV — some retired',
    ma_s1_f4: 'FEVE stock — transferred to Renfe; surpluses possible',
    ma_s1_d1_type: 'Serie 440', ma_s1_d1_len: '20 m', ma_s1_d1_wt: '~38 tonnes', ma_s1_d1_best: '4–6 person office',
    ma_s1_d2_type: 'Serie 592', ma_s1_d2_len: '~26 m', ma_s1_d2_wt: '~45 tonnes', ma_s1_d2_best: '6–8 person office',
    ma_s1_d3_type: 'Talgo', ma_s1_d3_len: '~26 m', ma_s1_d3_wt: '~40 tonnes', ma_s1_d3_best: '6–10 person office',
    ma_s1_concl: 'Supply exists via Renfe, FEVE and private sellers. Old stock accessible; Renfe sells at auctions during fleet renewal.',
    ma_s2_trans_p: 'Specialist hauliers (Grupo Sesé, local). Methods: low-loader, crane. Permits vary by autonomous community.',
    ma_s2_r1_d: '50 km', ma_s2_r1_c: '€8,000–€14,000',
    ma_s2_r2_d: '200 km', ma_s2_r2_c: '€15,000–€28,000',
    ma_s2_r3_d: '500+ km', ma_s2_r3_c: '€25,000–€45,000+',
    ma_s2_req: 'Exceptional load permits, route survey, site access. Regulations vary by region.',
    ma_s2_siting_p: 'Heritage lines require road delivery. Urban sites need landowner agreement, planning, services. Platforms possible where Adif/Renfe allows.',
    ma_s3_p1: '~USD 0.8B (2024), ~10–12% CAGR. Drivers: remote work, wellbeing, lack of private space in offices.',
    ma_s3_p2: 'Madrid/Barcelona flexible: €25–45/m²; prime €60+/m².',
    ma_s3_r1_p: 'Local pod solutions', ma_s3_r1_pr: '€4,000–€12,000 + VAT', ma_s3_r1_c: '2–6 people',
    ma_s3_r2_p: 'Hot desk membership', ma_s3_r2_pr: '€120–€450/month', ma_s3_r2_c: '1',
    ma_s3_r3_p: 'Private office', ma_s3_r3_pr: '€400–€1,200+/desk/month', ma_s3_r3_c: '2–10',
    ma_s3_pos: 'Real carriages, heritage character, larger footprint (4–10 people). Target: SMEs, creative agencies, remote teams, coworking in Madrid, Barcelona, Valencia.',
    ma_s4_r1_proc: '€6,000', ma_s4_r1_trans: '€12,000', ma_s4_r1_conv: '€45,000', ma_s4_r1_tot: '€63,000',
    ma_s4_r2_proc: '€18,000', ma_s4_r2_trans: '€22,000', ma_s4_r2_conv: '€110,000', ma_s4_r2_tot: '€150,000',
    ma_s4_r3_proc: '€40,000', ma_s4_r3_trans: '€28,000', ma_s4_r3_conv: '€165,000', ma_s4_r3_tot: '€233,000',
    ma_s5_p1: '4-person cabin: €2,200–€3,800/month at €550–€950/desk. Payback: ~4–5 years at 75–80% occupancy. Pricing €800+/desk improves viability.',
    ma_s5_p2: 'Portfolio of 5–10 cabins improves margins. B2B and corporate lets improve unit economics.',
    ma_s6_r1_r: 'Supply volatility', ma_s6_r1_m: 'Follow Renfe auctions; contact during fleet replacement',
    ma_s6_r2_r: 'Transport cost', ma_s6_r2_m: 'Site near source; batch moves',
    ma_s6_r3_r: 'Planning', ma_s6_r3_m: 'Early engagement with municipalities; permitted development where possible',
    ma_s6_r4_r: 'Land access', ma_s6_r4_m: 'Partner with Adif, business parks, heritage lines',
    ma_s7_r1_f: 'Availability', ma_s7_r1_a: 'Moderate — Renfe stock accessible; periodic auctions',
    ma_s7_r2_f: 'Logistics', ma_s7_r2_a: 'Manageable — specialist hauliers exist',
    ma_s7_r3_f: 'Demand', ma_s7_r3_a: 'Strong — office pod market growing',
    ma_s7_r4_f: 'CapEx per cabin', ma_s7_r4_a: '€63k–€233k depending on spec',
    ma_s7_r5_f: 'ROI', ma_s7_r5_a: '4–5 year payback feasible at 75–80% occupancy',
    ma_s7_rec: 'Pilot with 1–2 carriages in Madrid or Barcelona. Target €80–120k all-in per cabin, premium pricing. Validate demand before scaling.',
    ma_sources: 'Sources: Renfe, FEVE, Grupo Sesé, Madrid/Barcelona coworking. Figures are indicative.',
    },
    uk: {},
    es: {},
  },
};
